import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// this file like the index.html in react.js;


// ## Understood ##

// Start Configuring Fonts .
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// ## Ended Configuring Fonts ##


// End Configuring Fonts .

export const metadata = {
  title: "First Next App 😁 ",
  description: "Generated by Hazem",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
